# Generated by Django 4.2.11 on 2026-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_category_tag_post_placement_post_category_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='AI 요약')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'AI 요약',
                'verbose_name_plural': 'AI 요약',
            },
        ),
    ]
