# Generated by Django 5.2.11 on 2026-02-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_aisummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='prompt_template',
            field=models.TextField(default='위 글들을 바탕으로, 이 블로그 작가가 최근 어떤 생각을 하고 있는지 정리하는 짧은 글을 작성해주세요.\n\n- 글을 추천하거나 가이드하지 말 것\n- 카테고리 설명이나 목록 나열 금지\n- 글쓴이의 최근 관심사, 고민, 시선의 흐름을 하나의 맥락으로 묶어 서술\n- 담백하고 사적인 에세이 톤\n- 분석적이지 않고, 정리된 사유처럼 작성\n- 존대말의 종결형식을 사용\n- HTML 형식 (h3, p 태그만 사용)\n- 전체 길이 300자 내외', verbose_name='프롬프트'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='system_message',
            field=models.TextField(default='당신은 블로그의 글을 읽고, 작가의 최근 생각을 조용히 정리해주는 편집자입니다.', verbose_name='시스템 메시지'),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='AI 요약'),
        ),
    ]
