# Generated by Django 5.2.11 on 2026-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_aisummary_prompt_template_aisummary_system_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='suggest_prompt',
            field=models.TextField(default='다음 문장을 더 자연스럽고 명확하게 다듬어주세요.\n\n원문:\n{text}\n\n규칙:\n- 원문의 의미와 톤을 유지할 것\n- 문법, 맞춤법, 어색한 표현만 교정\n- 이미 충분히 좋은 문장이면 원문을 그대로 반환\n- 교정된 문장만 반환 (설명 없이)\n- HTML 태그 없이 순수 텍스트만 반환', verbose_name='제안 프롬프트'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='suggest_system',
            field=models.TextField(default='당신은 글을 다듬어주는 편집자입니다. 교정된 문장만 반환합니다.', verbose_name='제안 시스템 메시지'),
        ),
    ]
