# Generated by Django 5.2.11 on 2026-02-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
            ],
            options={
                'verbose_name': '문의 메시지',
                'verbose_name_plural': '문의 메시지',
                'ordering': ['-created_at'],
            },
        ),
    ]
